include: package:flutter_lints/flutter.yaml

linter:

  rules:
    avoid_print: false
    prefer_single_quotes: true
    curly_braces_in_flow_control_structures: false
    avoid_function_literals_in_foreach_calls: false
